// <auto-generated />
namespace GesColleges.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AssociationNoteEnseignant2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AssociationNoteEnseignant2));
        
        string IMigrationMetadata.Id
        {
            get { return "202105070954517_AssociationNoteEnseignant2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
